### ISSUE TITLE
Timer overflow is not handled correctly

### ISSUE THREAD

**Issue by hso-esk** [hso-esk/emb6#1]
Currently timer overflows are not handled correctly. E.g. if a timeout is registered just before an overflow this might become critical since the resulting overflow within the tickcounter is not handled.

**Comment by edschmitt** [comment]
Instead always calculating "expired-time = actual-time - start-timer" a timer overflow will be noted.
If the actual-time value is smaler than the start-time value a overflow happend and the calculation is "expired-time = OVERFLOW_VALUE - start-time + actual-time + 1".
Attention: if the data type of the timer value changes the overflow value has to be adapted. Actually the data type is 32 unsigned integer.
