### ISSUE TITLE
Add socket files from Contiki

### ISSUE THREAD

**Issue by ayushev** [hso-esk/emb6#21]
Integrate Contiki's socket interface into emb6.
For this you need to add files from Contiki namelly [tcp-socket](https://github.com/contiki-os/contiki/blob/master/core/net/ip/tcp-socket.c) and [udp-socket](https://github.com/contiki-os/contiki/blob/master/core/net/ip/udp-socket.c).
Strip files from protothreads off
rest-engine transformation can be used as an example of howto:
[Before](https://github.com/contiki-os/contiki/blob/master/apps/rest-engine/rest-engine.c) and [after](https://github.com/hso-esk/emb6/blob/develop/emb6/src/apl/rest-engine/rest-engine.c)

**Comment by edschmitt** [comment]
- the new files are located in emb6/src/tport/_.c and emb6/inc/tport/_.h
- the file is adapted as less as possible to the emb6 stack
- the functions of this modules represent the BSD-like interface bewteen application and transport layer
