### ISSUE TITLE
SCons build fails if "CPPDEFINES" was not set

### ISSUE THREAD

**Issue by mschappa** [hso-esk/emb6#39]
emb6/SConscript fails at line 127 (genv.MergeFlags({'CPPDEFINES' : mmac})) if CPPDEFINES is empty

**Comment by mschappa** [comment]
scons: Reading SConscript files ...

> Configure project for extif application and  configuration
> ./target/bsp/native/SConscript
> AttributeError: 'str' object has no attribute 'reverse':
>   File "/home/mschappa/projects/hso/emb6/devel/emb6/SConstruct", line 143:
>     file = genv.SConscript('SConscript', variant_dir=build_dir, duplicate=0, exports=args)
>   File "/usr/lib/scons/SCons/Script/SConscript.py", line 546:
>     return _SConscript(self.fs, _files, *_subst_kw)
>   File "/usr/lib/scons/SCons/Script/SConscript.py", line 260:
>     exec _file_ in call_stack[-1].globals
>   File "/home/mschappa/projects/hso/emb6/devel/emb6/SConscript", line 221:
>     prep_board()
>   File "/home/mschappa/projects/hso/emb6/devel/emb6/SConscript", line 203:
>     prep_board_if(trg_path, board_conf['brd'])
>   File "/home/mschappa/projects/hso/emb6/devel/emb6/SConscript", line 127:
>     genv.MergeFlags({'CPPDEFINES' : mmac})
>   File "/usr/lib/scons/SCons/Environment.py", line 852:
>     orig.reverse()

**Comment by mschappa** [comment]
can be tested with branch "feature/virtualbr" and target "if_lux"

**Comment by hso-esk** [comment]
obsolete due to new SCons layout
