### ISSUE TITLE
error sending big packets

### ISSUE THREAD

**Issue by plehmann123** [hso-esk/emb6#5]
bigger packets to be sent get lost in the network layer

**Comment by ayushev** [comment]
Dear plehmann123, can you describe this issue more precisely, packets from where to where, what size of packets and so one.

**Comment by plehmann123** [comment]
Dear ayushev,
e.g. coap response packets with blocksize 64
there is no problem with blocksize 32
I think the application layer works fine.

**Comment by edschmitt** [comment]
solved in #11

**Comment by edschmitt** [comment]
The resource handler for the rf_info resource was not correct implemented. If the data to send was bigger as as the coap block size the error occured.
Here the data buffer was not correct handled block by block to send the correct part of string. The solution was for this problem the usage of the REST.get_query_variable(). It handles the correct usage of the frame to send with the return of the buffer length.

There was also a fragmentation problem that was solved by increasing the amount of queue buffers count from 1 to 4
#define QUEUEBUF_CONF_NUM 4
#define QUEUEBUF_CONF_REFR_NUM 4
